// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdZDjfOnMhAGOSNfp9URE6V_EBz433Lc',
    appId: '1:259917866105:web:ddd51af4b767488c9760a8',
    messagingSenderId: '259917866105',
    projectId: 'chat-test-7f044',
    authDomain: 'chat-test-7f044.firebaseapp.com',
    storageBucket: 'chat-test-7f044.appspot.com',
    measurementId: 'G-F7K4ZXPEXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yhVmoI_2rDZRFo1_0uLfWFg31GUDh1o',
    appId: '1:259917866105:android:acb8ca27c33c863e9760a8',
    messagingSenderId: '259917866105',
    projectId: 'chat-test-7f044',
    storageBucket: 'chat-test-7f044.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdOqisI_TuWExslGytIN0k-ORY9lm2LdQ',
    appId: '1:259917866105:ios:aa746229c19fcb6a9760a8',
    messagingSenderId: '259917866105',
    projectId: 'chat-test-7f044',
    storageBucket: 'chat-test-7f044.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdOqisI_TuWExslGytIN0k-ORY9lm2LdQ',
    appId: '1:259917866105:ios:d1e5a45b3f1345ee9760a8',
    messagingSenderId: '259917866105',
    projectId: 'chat-test-7f044',
    storageBucket: 'chat-test-7f044.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
